### PR TITLE
Feature/localization

### PR DESCRIPTION
**Pull request by LB31**
- The current implementation supports only English and German
- Each text is responsible for its own translation

Example for usage:
LocalizationService().getLocalization(
english: "Settings", 
german: "Einstellungen");

### CODE REVIEW

**Review by dephiloper — CHANGES_REQUESTED** [review]
My Opinion: I think this is not a good approach to acheive localization in apps. The problem is that all the translations are distributed all over the app. It would make much more sense if there are specific files for localization like german.yaml or .json etc. There you could see all the localization on one view. 
Example: https://medium.com/flutter-community/flutter-internationalization-the-easy-way-using-provider-and-json-c47caa4212b2
The beauty is that you are able to specify a key only inside the pages and the correct string will be selected from the localization files/dictionary.

Your approch makes the whole app logic more verbose which not good practice imo.

**Comment by jakubprogramming** [comment]
I would normally agree with @dephiloper, but given that we have less than 2 weeks left I would recommend just going with the implementation we have. It will work and we will have two languages with no extra effort. 

lets go and work on the real issues instead

**Comment by dephiloper** [comment]
> I would normally agree with @dephiloper, but given that we have less than 2 weeks left I would recommend just going with the implementation we have. It will work and we will have two languages with no extra effort.
> 
> lets go and work on the real issues instead

@jakubprogramming 
Alright then please review the PR and merge when there is no issue with it.

**Review by jakubprogramming — CHANGES_REQUESTED** [review]
I made some changes.
"Einrichtung" does not sound good in German and does not really make it clear what we are doing there. I changed it to "Route Planen". 
Furthermore you forgot to translate date to datum. 
I added this for you.


The entire "share" functionality is not localised at all.
Please add this and then we can approve this.

**Comment by LB31** [comment]
I agree with @dephiloper that the other way would be the cleaner solution. And I also had it in mind. 

But considering our deadline and the more pragmatic way for all devs not to have to change multiple files jut to translate only small phrases, the current implementation makes more sense for me.

Thanks for the small fixes @jakubprogramming 

The sharing is now also translated.

**Review by dephiloper — APPROVED** [review]
approve without personally approving it

**Review by jakubprogramming — APPROVED** [review]
I had to fix a bunch of merge conflicts but now it works all good.

**Pull request merged**
