### PR TITLE
Feature/improve route drawing

### PR DESCRIPTION
**Pull request by jakubprogramming**
Lines are not transparent so that street names can be read.
Also the size of the starting point circle is slightly reduced.

Furthermore I created an overlay that indicates what the colors red and green mean (start & finish).

This is a rather small PR so reviewing it should not take all that long.

### CODE REVIEW

**Review by LB31 — APPROVED** [review]
The build does what it should. The street names are readable. The Start/Finish UI is a meaningful addition

**Review by mayo-s — CHANGES_REQUESTED** [review]
null pointer on clearLines when executing calculations on routePref pages.
Please double check

Screenshot 2020-01-11 at 22 39 51

**Comment by LB31** [comment]
@mayo-s 
Could you document how to reconstruct the occurrence of this error? 
I don't get it when executing the calculation from the pref page.
Neither on switching the route or switching the direction.

**Comment by jakubprogramming** [comment]
I am not able to reproduce the null pointer exception. 
Can you please explain under what circumstances this has happened to you?

**Comment by jakubprogramming** [comment]
@mayo-s  What are you trying to say with
"null pointer on clearLines when executing calculations on routePref pages.
Please double check"? 

The routes are not calculated on the routePrefs page, but inside the routePreview page

**Comment by mayo-s** [comment]
Seems like the npe only occurs when using the emulator.
Working on my phone.

**Review by mayo-s — APPROVED** [review]

**Pull request merged**
