### PR TITLE
Feature/draw pois

### PR DESCRIPTION
**Pull request by jakubprogramming**
POIS are drawn as circles initially.
When zoom is >14 symbols are shown instead.
These become circles again once zoom < 14.

### CODE REVIEW

**Comment by RomanKrajewski** [comment]
Just tried this. The images are not shown on my device (android emulator)..

**Review by RomanKrajewski — CHANGES_REQUESTED** [review]
Images are not shown when running in android emulator

**Comment by jakubprogramming** [comment]
I cannot verify whether or not images are shown on the emulator because I always get an exception when trying to calculate routes on an emulator. 

On the device everything works perfectly. Do we our app to work on an emulator in all cases?


It seems to me the Geocoder plugin is not working on emulators for some reason

[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(failed, Failed, null)
E/flutter ( 9280): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter ( 9280): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter ( 9280): <asynchronous suspension>
E/flutter ( 9280): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter ( 9280): #3      LocalGeocoding.findAddressesFromCoordinates (package:geocoder/services/local.dart:13:41)
E/flutter ( 9280): #4      HikingRoute.buildTitle (package:hiking4nerds/services/route.dart:29:49)
E/flutter ( 9280): #5      _RouteListState.buildRouteTitles (package:hiking4nerds/pages/setup/route_list.dart:70:38)
E/flutter ( 9280): #6      _RouteListState.calculateRoutes (package:hiking4nerds/pages/setup/route_list.dart:51:11)
E/flutter ( 9280): <asynchronous suspension>
E/flutter ( 9280): #7      _RouteListState.initState (package:hiking4nerds/pages/setup/route_list.dart:27:5)
E/flutter ( 9280): #8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4456:58)
E/flutter ( 9280): #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4302:5)
E/flutter ( 9280): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
E/flutter ( 9280): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
E/flutter ( 9280): #12     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5570:14)
E/flutter ( 9280): #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
E/flutter ( 9280): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
E/flutter ( 9280): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4344:16)
E/flutter ( 9280): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
E/flutter ( 9280): #17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4307:5)
E/flutter ( 9280): #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4302:5)
E/flutter ( 9280): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
E/flutter ( 9280): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
E/flutter ( 9280): #21     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5570:14)
E/flutter ( 9280): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
E/flutter ( 9280): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
E/flutter ( 9280): #24     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5570:14)
E/flutter ( 9280): #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
E/flutter ( 9280): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
E/flutter ( 9280): #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4344:16)
E/flutter ( 9280): #28     Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
E/flutter ( 9280): #29     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4307:5)
E/flutter ( 9280): #30     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4482:11)
E/flutter ( 9280): #31     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4302:5)
E/flutter ( 9280): #32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
E/flutter ( 9280): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
E/flutter ( 9280): #34     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5570:14)
E/flutter ( 9280): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
E/flutter ( 9280): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
E/flutter ( 9280): #37     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5570:14)
E/flutter ( 9280): #38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
E/flutter ( 9280): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
E/flutter ( 9280): #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4344:16)
E/flutter ( 9280): #41     Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
E/flutter ( 9280): #42     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4307:5)
E/flutter ( 9280): #43     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4482:11)

**Comment by RomanKrajewski** [comment]
something else just came to my mind: 
now that we have 3 pois max on each route, we might want to always show the icons. no need to hide them if there aren‘t too many of them

i‘ll test this later on a real device and merge it afterwards. emulator is probably not that important

**Review by dephiloper — APPROVED** [review]

**Comment by jakubprogramming** [comment]
Hey @RomanKrajewski  could we not keep the current implementation of the algorithm (with 3 pois) but still show all other poi's that just happen to lay on the route that was calculated? 

We don't try to find any more than 3, but if they are on our existing route anyway (without going toward them) why not shown them?

**Comment by jakubprogramming** [comment]
@dephiloper great changes. I can't review my on MR but I think we should merge now!

**Review by RomanKrajewski — APPROVED** [review]

**Pull request merged**
