### PR TITLE
WIP Feature/update route v2

### PR DESCRIPTION
**Pull request by jakubprogramming**
I simplified the update route logic and fixed any errors that have occurred during the last couple of weeks of development.

As a result much less code is needed for updating the route and the code should be easier to understand now.

I tested this thoroughly on my device but I recommend you guys to test it as well.
In case you don't want to go outside and take a hike you can use the app "Fake GPS" from google play to mock your device location.

### CODE REVIEW

**Comment by dephiloper** [comment]
I encountered several issues while trying to test the functionality.
First when my location settings are dissabled the user now doesn't even get ask anymore for a permission or to switch to location settings on. For the second issue I appended a screenshot. When the start and end point intersect and the user starts his tour and moves to the intersection point the whole route is marked as passed which is not the correct behavior.

78bf1621-2d73-4d0b-888b-55eeba72c9e2

Because of the functional errors I did not continue the review.

**Review by dephiloper — CHANGES_REQUESTED** [review]
See functional issues mentioned in the conversation tab.

**Comment by jakubprogramming** [comment]
Location is now requested on map created once again

**Comment by jakubprogramming** [comment]
for the other issue I currently don't see any reason to take action.
When Roman resolves the intersection problem this will be fine.
Furthermore I think this is a great improvement to the old implementation so imo we should merge this even if slight adjustments are necessary still

**Comment by dephiloper** [comment]
> for the other issue I currently don't see any reason to take action.
When Roman resolves the intersection problem this will be fine.
Furthermore I think this is a great improvement to the old implementation so imo we should merge this even if slight adjustments are necessary still

I don't think roman will fix the intersection problem because it isn't a real problem. Yes you are right the implementation is less confusing, but does not output the correct solution and should be modified.

**Comment by jakubprogramming** [comment]
Merging feature/route_preview_header introduced some errors.
The new drawing of routes did not work together with the updateRoute function very well.
Also the "starting line"  (green) was sometimes drawn underneath the blue. I now make sure to draw it after the blue line so that it is always on top.

**Review by dephiloper — APPROVED** [review]

**Pull request merged**
