### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by mayo-s**
On home page menu and hikingmap are now within a Stack and independent from each other.
howto page is obsolete.
help page filled with some content.

### CODE REVIEW

**Comment by dephiloper** [comment]
@mayo-s why are you merging into master? Isn't the default behavior to only merge in master when we are creating a release candidate (see https://m.infos.seibert-media.net/Productivity/Git-Workflows+-+Der+Gitflow-Workflow.html)? I think you should develop on a separate feature branch next time and we should not merge this into master for now.

@jakubprogramming have you already reviewed this? Changes should be done on the develop branch for this single time.

**Comment by jakubprogramming** [comment]
@dephiloper 

I have reviewed this already and approved it to be merged into the develop branch a couple of days ago.

**Comment by mayo-s** [comment]
Only merge into develop until further notice

**Comment by jakubprogramming** [comment]
Since we dont really have any "releases" until the end of the semster (Release 1.0 or whatever)
I would say that any functionality that has been tested and adds significant value to the application can be merged into master.

**Pull request closed without merging**
