### PR TITLE
Feature/plan route --> Initial Page for selecting the starting location of the hiking trip

### PR DESCRIPTION
**Pull request by jakubprogramming**
Users may choose to use their current GPS location, type in an address or move the marker around on the map.

### CODE REVIEW

**Review by dephiloper — CHANGES_REQUESTED** [review]
Your changes are perfectly fine like we discussed! Only issue is that you used a search button where are search bar would be more fitting: e.g. https://pub.dev/packages/floating_search_bar

In addition i would make the start button bigger and move the location button to the bottom right, a little bit over the start button.

**Comment by jakubprogramming** [comment]
Done!

The searchBar thing took much longer than it should have.
The problem is that I had to manually recreate the widget that is automatically created by the showSearch function (https://api.flutter.dev/flutter/material/showSearch.html). 

If I had not done this, the searchbar would have looked differently upon clicking it.
Anyway the result is not 100% accurate, but like 99%.

I'll leave the last percent for later. 
But for now I believe we can merge this.

**Review by dephiloper — APPROVED** [review]

**Comment by dephiloper** [comment]
Looks got so far. There are additional things i would change, but I think we can implement them later:
* I would have used a floating search bar because it looks more familiar to a maps user
* after selecting an location in the search bar, the name of the location is not visible in the search bar

**Comment by jakubprogramming** [comment]
Not really into reinventing the wheel given our timeframe. 
ShowSearch is the default flutter way for doing searches. 
Thats why I used it.

after selecting a location in the search bar, the name of the location is not visible in the search bar --> yes that makes perfect sense

**Pull request merged**
